### ISSUE TITLE
No such property: awsProfile for class: com.github.skhatri.s3aws.plugin.S3Extension_Decorated

### ISSUE THREAD

**Issue by gsindholt** [skhatri/gradle-s3-plugin#4]
I run gradle 2.3 (in Eclipse). When I try to run the upload task with awsProfile = 'default' it fails with the error below. If I remove the awsProfile = 'default' line all together, the task runs succesfully.

Caused by: groovy.lang.MissingPropertyException: No such property: awsProfile for class: com.github.skhatri.s3aws.plugin.S3Extension_Decorated
    at org.gradle.api.internal.plugins.ExtraPropertiesDynamicObjectAdapter.setProperty(ExtraPropertiesDynamicObjectAdapter.java:46)
    at org.gradle.api.internal.CompositeDynamicObject.setProperty(CompositeDynamicObject.java:119)
    at com.github.skhatri.s3aws.plugin.S3Extension_Decorated.setProperty(Unknown Source)
    at build_7o2efv5kj8qfnq8alms8ho2gn9$_run_closure6.doCall(/Users/glenniesindholt/Documents/work/workspace/knowledge-graph-lib/build.gradle:45)
    at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:59)
    at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:145)
    at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:69)
    at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:207)
    at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:147)
    at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
    at build_7o2efv5kj8qfnq8alms8ho2gn9.run(/Users/glenniesindholt/Documents/work/workspace/knowledge-graph-lib/build.gradle:43)
    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)

**Comment by adrijardi** [comment]
I had the same issue, the cause was that the version on the Maven repositories is not the same (version 1.0.0 in Maven doesn't have awsProfile) you can just not use that and it will load the default profile anyway as you can see in here http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/profile/ProfileCredentialsProvider.html#ProfileCredentialsProvider()

**Comment by skhatri** [comment]
You can use this
http://repo1.maven.org/maven2/com/github/skhatri/gradle-s3-plugin/1.0.3/

awsProfile was a recent addition and was not present in 1.0.0 like mentioned above.

**Comment by skhatri** [comment]
or you may use the latest 1.0.4. It uses the default provider chain which will pick default profile.
http://repo1.maven.org/maven2/com/github/skhatri/gradle-s3-plugin/1.0.4/
